environ:
  seed: 5
  deterministic: False
model:
  name: "dorn"
  # pretrained_model не про resnet. Он зашит дальше
  pretrained_model:
  params:
    ord_num: 90
    gamma: -0.97
    beta: 90.0
    input_size: [352, 470]
    kernel_size: 16
    pyramid: [8, 12, 16]
    batch_norm: False
    discretization: "SID"
    pretrained: True
data:
  name: "kitti"
  split: ["trainval", "selected_val"]
  path: '/media/data/datasets/penitto/kitti'
  tr_crop_size: [352, 470]
  te_crop_size: [352, 470]
  norm_type: "imagenet-norm"
solver:
  epochs: 14
  batch_size: 1
  step_decay: 1
  optimizer:
    name: 'SGD'
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0005
  lr_policy:
    name: 'poly'
    params:
      gamma: 0.9
      n_iteration: 300636
# apex:
#   amp_used: False
#   opt_level: "O1"
#   keep_batchnorm_fp32:
#   loss_scale:
vis_config:
  name: "dorn"
snap:
  path: "/home/penitto/mono_depth/networks/dorn/snaps"
