environ:
  seed: 5
  deterministic: False
model:
  name: "dorn"
  pretrained_model:
  params:
    ord_num: 90
    gamma: -1.0
    beta: 117.0
    input_size: [270, 480]
    kernel_size: 16
    pyramid: [4, 8, 16]
    batch_norm: True
    discretization: "SID"
    pretrained: True
data:
  name: "evo"
  split: ['train', 'val']
  path: '/media/data/datasets/bag_depth'
  tr_crop_size: [270, 480]
  te_crop_size: [270, 480]
  norm_type: "norm"
solver:
  epochs: 30
  batch_size: 2
  step_decay: 1
  optimizer:
    name: 'Adam'
    params:
      lr: 0.0001
      # momentum: 0.9
      weight_decay: 0.0005
      eps: 1e-5
  lr_policy:
    name: 'constant'
    # params:
    #   T_max: 500
    #   eta_min: 0.00001
# apex:
#   amp_used: False
#   opt_level: "O1"
#   keep_batchnorm_fp32:
#   loss_scale:
vis_config:
  name: "dorn"
snap:
  path: "/home/penitto/mono_depth/networks/dorn/snaps"
