environ:
  seed: 5
  deterministic: False
model:
  name: "dorn"
  pretrained_model:
  params:
    ord_num: 90
    gamma: -1.0
    beta: 117.0
    input_size: [288, 512]
    kernel_size: 16
    pyramid: [8,12, 16]
    batch_norm: False
    discretization: "SID"
    pretrained: True
data:
  name: "evo"
  split: ['train', 'val']
  path: '/media/data/datasets/bag_depth'
  tr_crop_size: [288, 512]
  te_crop_size: [288, 512]
  norm_type: "norm"
solver:
  epochs: 30
  batch_size: 2
  step_decay: 1
  optimizer:
    name: 'SGD'
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0005
  lr_policy:
    name: 'poly'
    params:
      gamma: 0.9
      n_iteration: 300636
# apex:
#   amp_used: False
#   opt_level: "O1"
#   keep_batchnorm_fp32:
#   loss_scale:
vis_config:
  name: "dorn"
snap:
  path: "/home/penitto/mono_depth/networks/dorn/snaps_ev"
